# Generated by Django 4.2.3 on 2023-07-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="amount",
            field=models.CharField(max_length=10),
        ),
    ]
